# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyzJNI6Z_VhomCs-xfdXd5QfLgAxK-69
"""

!pip install fpdf

from fpdf import FPDF

# Ekspert tizimi
def oquvchi_yordam():
    print("O'quvchilarga yordam tizimiga xush kelibsiz!")
    print("Quyidagi mavzular bo'yicha yordam kerakligini tanlang:")
    print("1. Matematika")
    print("2. Fizika")
    print("3. Kimyo")
    print("4. Ingliz tili")

    tanlov = int(input("Mavzu raqamini kiriting (1-4): "))

    # Javoblarni baholash
    print("\nSavollarga javob berganingizni baholash uchun, o'zingizni baholang:")
    print("1: Juda yaxshi, 2: Yaxshi, 3: O'rtacha, 4: Yordam kerak")
    baho = int(input("Bahoni kiriting (1-4): "))

    # Tavsiyalarni aniqlash
    tavsiya, materiallar = tavsiyalar_aniqla(tanlov, baho)

    print(f"\nTavsiyalar: {tavsiya}")
    print(f"Tavsiya etilgan materiallar: {materiallar}")

    # Hisobotni eksport qilish
    hisobot_eksport(tanlov, baho, tavsiya, materiallar)

def tavsiyalar_aniqla(mavzu, baho):
    mavzular = {
        1: "Matematika",
        2: "Fizika",
        3: "Kimyo",
        4: "Ingliz tili"
    }

    materiallar = {
        1: ["Algebra kitobi", "YouTube: Algebra darslari", "Geometriya masalalari to'plami"],
        2: ["Fizika nazariyalari", "Amaliyot kitobi: Harakat qonunlari", "Video: Newton qonunlari"],
        3: ["Kimyo asoslari kitobi", "Kimyoviy reaksiyalar haqida video", "Laboratoriya mashg'ulotlari qo'llanmasi"],
        4: ["Grammar kitobi", "YouTube: Ingliz tili suhbatlari", "Listening amaliyotlari"]
    }

    tavsiya = {
        1: "Ajoyib! Davom eting.",
        2: "Yaxshi ishlayapsiz, ammo mavzularni mustahkamlash uchun amaliy mashqlar bajaring.",
        3: "Qo'shimcha ishlash kerak. Tavsiya etilgan materiallardan foydalaning.",
        4: "Yordam kerak. O'qituvchidan yoki qo'shimcha darslardan foydalaning."
    }

    mavzu_nomi = mavzular.get(mavzu, "Noma'lum mavzu")
    material = materiallar.get(mavzu, ["Material topilmadi"])
    tavsiya_text = tavsiya.get(baho, "Baholashda xatolik")

    return f"Mavzu: {mavzu_nomi}\n{tavsiya_text}", material

def hisobot_eksport(mavzu, baho, tavsiya, materiallar):
    mavzu_nomi = {
        1: "Matematika",
        2: "Fizika",
        3: "Kimyo",
        4: "Ingliz tili"
    }.get(mavzu, "Noma'lum mavzu")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="O'quvchi uchun yordam hisoboti", ln=True, align='C')
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Mavzu: {mavzu_nomi}", ln=True)
    pdf.cell(200, 10, txt=f"Tavsiyalar: {tavsiya}", ln=True)
    pdf.ln(10)
    pdf.cell(200, 10, txt="Qo'shimcha materiallar:", ln=True)
    for material in materiallar:
        pdf.cell(200, 10, txt=f"- {material}", ln=True)

    file_name = "oquvchi_yordam_hisoboti.pdf"
    pdf.output(file_name)
    print(f"\nHisobot '{file_name}' faylida saqlandi!")

# Tizimni ishga tushirish
oquvchi_yordam()